<a href="https://colab.research.google.com/github/amanjaiswal777/Fundamentals-Machine-Learning-algorithms/blob/master/Tensorflow/Customization_Basic/Tensors_and_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Tensorflow

import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

In [3]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))


# Operator overloading
print(tf.square(3) + tf.square(5))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)


In [4]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [5]:
import numpy as np

ndarray = np.ones([3, 3])

print(tf.multiply(ndarray, 42))

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [7]:
print(np.add(tf.multiply(ndarray, 42), 1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [8]:
print(tf.multiply(ndarray, 42).numpy())

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [10]:
x = tf.random.uniform([3, 3])

print(tf.config.list_physical_devices("GPU"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [11]:
print(x.device.endswith('GPU:0'))

True


In [13]:
import time


def time_matmul(x):
  start = time.time()

  for loop in range(10):
    tf.matmul(x, x)

  result = time.time() - start

  print(1000*result)

print('On CPU:')
with tf.device("CPU:0"):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

#Exceution on GPU
if tf.config.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
608.4895133972168
On GPU:
1534.4009399414062


In [15]:
# Creating a source Dataset

ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

#Creating a CSV file

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write(""" Line 1
  Line 2
  Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [19]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [20]:
for x in ds_tensors:
  print(x)

tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([ 9 16], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)


In [21]:
for x in ds_file:
  print(x)

tf.Tensor(
[[[b' Line 1' b'  Line 2']
  [b'  Line 3' b'  ']]], shape=(1, 2, 2), dtype=string)
